/* Resource File Indices for WORLDCLK */

#define TIME     0   /* Form/Dialog */

#define MAIN     1   /* Form/Dialog */
#define MAINCOOR 1   /* TEXT in tree MAIN */
#define MAINMENU 2   /* BOXCHAR in tree MAIN */
#define MAINSIZE 3   /* BOXCHAR in tree MAIN */

#define POP      2   /* Form/Dialog */
#define POPTION  1   /* STRING in tree POP */
#define PPLACE   2   /* STRING in tree POP */
#define PSET     3   /* STRING in tree POP */
#define PSAVE    4   /* STRING in tree POP */
#define PABOUT   5   /* STRING in tree POP */

#define EDITCITY 3   /* Form/Dialog */
#define EDBOX    1   /* BOX in tree EDITCITY */
#define EDPMI    2   /* BOXCHAR in tree EDITCITY */
#define EDPLACE  3   /* FTEXT in tree EDITCITY */
#define EDPPL    4   /* BOXCHAR in tree EDITCITY */
#define EDLED    6   /* FTEXT in tree EDITCITY */
#define EDLEDM   7   /* FTEXT in tree EDITCITY */
#define EDLN     8   /* BOXCHAR in tree EDITCITY */
#define EDLS     9   /* BOXCHAR in tree EDITCITY */
#define EDOED    10  /* FTEXT in tree EDITCITY */
#define EDOEDM   11  /* FTEXT in tree EDITCITY */
#define EDOE     12  /* BOXCHAR in tree EDITCITY */
#define EDOW     13  /* BOXCHAR in tree EDITCITY */
#define EDGED    15  /* FBOXTEXT in tree EDITCITY */
#define EDGMN    16  /* FBOXTEXT in tree EDITCITY */
#define EDGW     17  /* BOXCHAR in tree EDITCITY */
#define EDGE     18  /* BOXCHAR in tree EDITCITY */
#define EDAS     19  /* BUTTON in tree EDITCITY */
#define EDAH     21  /* BUTTON in tree EDITCITY */
#define EDAD     23  /* BUTTON in tree EDITCITY */
#define EDSN     25  /* BUTTON in tree EDITCITY */
#define EDSNS    26  /* BUTTON in tree EDITCITY */
#define EDSEW    27  /* BUTTON in tree EDITCITY */
#define EDNEW    28  /* BUTTON in tree EDITCITY */
#define EDDEL    29  /* BUTTON in tree EDITCITY */
#define EDGOTO   30  /* BUTTON in tree EDITCITY */
#define EDOK     31  /* BUTTON in tree EDITCITY */

#define OPTIONS  4   /* Form/Dialog */
#define OPAMPM   1   /* BUTTON in tree OPTIONS */
#define OP24     2   /* BUTTON in tree OPTIONS */
#define OPDATE   3   /* BUTTON in tree OPTIONS */
#define OPHOUR   4   /* BUTTON in tree OPTIONS */
#define OPCOOR   5   /* BUTTON in tree OPTIONS */
#define OPTIME   6   /* BUTTON in tree OPTIONS */
#define OPOK     7   /* BUTTON in tree OPTIONS */
#define OPCANC   8   /* BUTTON in tree OPTIONS */

#define EDITDT   5   /* Form/Dialog */
#define EDDATE   1   /* FTEXT in tree EDITDT */
#define EDTIME   2   /* FTEXT in tree EDITDT */
#define EDAMPM   3   /* IBOX in tree EDITDT */
#define EDAM     4   /* BUTTON in tree EDITDT */
#define EDPM     5   /* BUTTON in tree EDITDT */
#define ED24     6   /* STRING in tree EDITDT */
#define EDDOK    7   /* BUTTON in tree EDITDT */

#define ABOUT    6   /* Form/Dialog */
#define AICON    1   /* BOX in tree ABOUT */

#define DAYPOP   7   /* Form/Dialog */

#define CLKICON  8   /* Form/Dialog */

#define NOWIND   0   /* Alert String */

#define ALVDI    1   /* Alert String */

#define ALDAT    2   /* Alert String */

#define BADHOUR  3   /* Alert String */

#define BADHOUR2 4   /* Alert String */

#define BADTIME  5   /* Alert String */

#define BADDATE  6   /* Alert String */

#define BADCOOR  7   /* Alert String */

#define BADGMT   8   /* Alert String */

#define NOGEM    9   /* Alert String */

#define GEMMEM   10  /* Alert String */

#define NOHERE   11  /* Alert String */

#define SAVEME   12  /* Alert String */

#define BADDAT   13  /* Alert String */

#define CITROOM  14  /* Alert String */

#define NOCITY   15  /* Alert String */

#define ACCNAME  16  /* Free String */

#define YESTER   17  /* Free String */

#define TODAY    18  /* Free String */

#define TOMORR   19  /* Free String */

#define IDT      20  /* Free String */
